# Generated by Django 6.0 on 2025-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
