# Generated by Django 6.0 on 2025-12-13 16:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='approved',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('aprobado', 'Aprobado'), ('denegado', 'Denegado')], default='en_espera', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2025, 12, 13)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2025, 12, 13)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
